/*
 * @Description: This is a description
 * @Author: Jin Tang
 * @Date: 2025-01-24 10:09:42
 * @LastEditors: Jin Tang
 * @LastEditTime: 2025-01-24 17:09:59
 */
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export { }
declare global {
  // const MessagePlugin: typeof import('tdesign-vue-next')['MessagePlugin']
}
